# Generated by Django 3.2.12 on 2022-02-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0002_site_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='construction',
            field=models.CharField(default='Iron', max_length=255),
            preserve_default=False,
        ),
    ]
