# Generated by Django 3.2.12 on 2022-02-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0003_site_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
