# Generated by Django 3.2.12 on 2022-02-20 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wrecks', '0004_auto_20220220_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(choices=[('ME', 'Member'), ('GU', 'Guest'), ('AD', 'Admin'), ('MU', 'Museum'), ('OF', 'Offline')], default='GUEST', max_length=2)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('authors', models.ManyToManyField(to='wrecks.People')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='wrecks.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
