# Generated by Django 3.2.12 on 2022-02-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0005_people_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='authors',
            field=models.ManyToManyField(to='wrecks.People'),
        ),
    ]
