# Generated by Django 3.2.12 on 2022-02-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0006_report_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='reports',
            field=models.ManyToManyField(to='wrecks.Report'),
        ),
    ]
