# Generated by Django 3.2.12 on 2022-02-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0009_rename_people_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='publications/'),
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
