# Generated by Django 3.2.12 on 2022-02-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0012_auto_20220220_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='abstract',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='owner',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='sinking',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='size',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='underwater',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
