# Generated by Django 3.2.12 on 2022-02-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0013_auto_20220221_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1200, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('leaders', models.ManyToManyField(to='wrecks.Person')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='project',
            field=models.ManyToManyField(to='wrecks.Project'),
        ),
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ManyToManyField(to='wrecks.Project'),
        ),
    ]
