# Generated by Django 3.2.12 on 2022-02-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0014_auto_20220221_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='project',
            field=models.ManyToManyField(blank=True, to='wrecks.Project'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='reports',
            field=models.ManyToManyField(blank=True, to='wrecks.Report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ManyToManyField(blank=True, to='wrecks.Project'),
        ),
    ]
