# Generated by Django 3.2.12 on 2022-02-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0015_auto_20220221_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='active',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
    ]
