# Generated by Django 3.2.12 on 2022-02-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0016_auto_20220222_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, choices=[('ME', 'Member'), ('GU', 'Guest'), ('AD', 'Admin'), ('MU', 'Museum'), ('OF', 'Offline')], default='GU', max_length=2),
        ),
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='publications'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='site',
            field=models.ManyToManyField(blank=True, to='wrecks.Site'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports'),
        ),
    ]
