# Generated by Django 3.2.12 on 2022-02-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0017_auto_20220223_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/reports'),
        ),
    ]
