# Generated by Django 3.1 on 2022-02-23 08:46

from django.db import migrations, models
import wrecks.models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0024_auto_20220223_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='publications'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=wrecks.models.report_date_directory_path),
        ),
    ]
