# Generated by Django 3.1 on 2022-02-24 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wrecks.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wrecks', '0025_auto_20220223_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('file', models.ImageField(blank=True, null=True, upload_to=wrecks.models.report_date_directory_path)),
                ('authors', models.ManyToManyField(to='wrecks.Person')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='wrecks.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
