# Generated by Django 3.1 on 2022-02-24 11:35

from django.db import migrations, models
import wrecks.models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0026_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='built_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=wrecks.models.photo_date_directory_path),
        ),
    ]
