# Generated by Django 3.1 on 2022-02-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0027_auto_20220224_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='region',
            field=models.CharField(blank=True, choices=[('PC', 'Perth Coast'), ('RI', 'Rottnest Island'), ('SW', 'Swan River'), ('SC', 'Southwest Coast'), ('SO', 'South Coast'), ('MW', 'Midwest Coast'), ('NW', 'Northwest Coast')], max_length=2),
        ),
    ]
