# Generated by Django 3.1 on 2022-02-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0028_site_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='dave_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='museum_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
