# Generated by Django 3.1 on 2022-02-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0030_auto_20220225_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
