# Generated by Django 3.1 on 2022-02-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0031_site_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='sketchfab_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
