# Generated by Django 3.1 on 2022-02-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0032_auto_20220226_0541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-order']},
        ),
        migrations.AddField(
            model_name='site',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
