# Generated by Django 3.1 on 2022-02-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0033_auto_20220226_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_end']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
