# Generated by Django 3.1 on 2022-03-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0035_report_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
