# Generated by Django 3.1 on 2022-03-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0036_auto_20220309_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
