# Generated by Django 3.1 on 2022-03-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrecks', '0038_auto_20220309_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
